### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by dodero4** [rzc0d3r/ESET-KeyGen#170]
Hi it has always worked until today, I downloaded the new version but it still doesn't work, what could be the problem?

-- WebDriver Auto-Installer --

[  INFO  ] Google Chrome version: 124.0.6367.61
[  INFO  ] Google Chrome webdriver version: 124.0.6367.60
[   OK   ] The driver has already been updated to the browser version!

[  INFO  ] Initializing chrome-webdriver for Windows

DevTools listening on ws://127.0.0.1:55637/devtools/browser/7db41d91-c58f-4c66-b436-8686fea81db9
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 903, in <module>
  File "main.py", line 314, in initSeleniumWebDriver
  File "selenium\webdriver\chrome\webdriver.py", line 45, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 61, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 208, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 292, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 347, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 229, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 124
Current browser version is 123.0.6312.124 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

**Comment by dodero4** [comment]
Solved reinstalling google chrome

**Comment by rzc0d3r** [comment]
Chrome downloaded the update and there are two versions in its files folder, the software gets confused and gives a false version to the driver installer

**Comment by rzc0d3r** [comment]
Go to chrome settings under About Browser and click reload (if there is an update)
