### ISSUE TITLE
Firefox method error!

### ISSUE THREAD

**Issue by RomaGly55Creations** [rzc0d3r/ESET-KeyGen#181]
[  INFO  ] Initializing chrome-webdriver for Windows 7
[ FAILED ] Traceback (most recent call last):
  File "C:\Users\User\Downloads\ESET-KeyGen-1.4.6.0\main.py", line 1033, in <module>
    driver = SharedTools.initSeleniumWebDriver(browser_name, webdriver_path, args['custom_browser_location'], (notargs['no_headless']))
  File "C:\Users\User\Downloads\ESET-KeyGen-1.4.6.0\main.py", line 444, in initSeleniumWebDriver
    driver = Firefox(options=driver_options, service=FirefoxService(executable_path=webdriver_path))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 69, in __init__super().__init__(command_executor=executor, options=options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 209, in __init__self.start_session(capabilities)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly clo
sed with status 0

Another fight coming around those lines, whenever it having an programmable-bot for Mozilla Firefox like chrome use?
Had been run via source code, cuz the executable form of live has to be rejected by great ESET, even when its end up to disable the whole HIPS.

Also miscellaneous, try check there's no conditions to put exe or source code in folder with space symbols?
I posted links to the emails with API, check it too.
Regards, Bug Hunter

**Comment by rzc0d3r** [comment]
I can't get anything from these logs. Try a different browser. Also, please describe in detail what you wrote after the logs. I don't get it

**Comment by RomaGly55Creations** [comment]
Just when its going to using an firefox key command correspondingly, was able to reach the error. However, this was rechecked once more, and got succeed response (maybe AV impact or delaying in something). But nextly, edge doesn't find itself at all.

**Comment by rzc0d3r** [comment]
edge does not work? What system do you have? Also send error logs when running with ```--edge```

**Comment by RomaGly55Creations** [comment]
Here.
C:\Users\User\Downloads\ESET-KeyGen-1.4.7.0\ESET-KeyGen-1.4.7.0>main
.py --edge --key

-- WebDriver Auto-Installer --

[ FAILED ] Traceback (most recent call last):
  File "C:\Users\User\Downloads\ESET-KeyGen-1.4.7.0\ESET-KeyGen-1.4.
7.0\main.py", line 677, in get_edge_version
    edge_version = subprocess.check_output(cmd, stderr=subprocess.DEVNULL).decod
e('utf-8').strip()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\sub
process.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\sub
process.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'powershell -Command "Get-ItemPropertyVal
ue -Path "HKCU:\SOFTWARE\Microsoft\Edge\BLBeacon" -Name "version""' returned non
-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\ESET-KeyGen-1.4.7.0\ESET-KeyGen-1.4.
7.0\main.py", line 1075, in <module>
    webdriver_path = webdriver_installer.webdriver_installer_menu(args['edge'],
args['firefox'])
  File "C:\Users\User\Downloads\ESET-KeyGen-1.4.7.0\ESET-KeyGen-1.4.
7.0\main.py", line 704, in webdriver_installer_menu
    browser_version = self.get_edge_version()
  File "C:\Users\User\Downloads\ESET-KeyGen-1.4.7.0\ESET-KeyGen-1.4.
7.0\main.py", line 680, in get_edge_version
    raise RuntimeError('WebDriverInstaller: microsoft edge is not detected insta
lled on your device!')
RuntimeError: WebDriverInstaller: microsoft edge is not detected installed on yo
ur device!

Still occurs in Win7, with installing over the existing edge. Also checked similar commands after browser select(key, business, account).

**Comment by rzc0d3r** [comment]
Did you force Edge to work on Windows 7? (Lol)

**Comment by rzc0d3r** [comment]
Maybe Edge v109?

**Comment by rzc0d3r** [comment]
First test:
![image](https://github.com/rzc0d3r/ESET-KeyGen/assets/106631540/c016a51d-9a9a-4d4c-a8c4-a42adf75236a)

**Comment by rzc0d3r** [comment]
try: [ESET-KeyGen-v1.6.7.1-DEV.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/15262736/ESET-KeyGen-v1.6.7.1-DEV.zip)

**Comment by RomaGly55Creations** [comment]
> try: [ESET-KeyGen-v1.6.7.1-DEV.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/15262736/ESET-KeyGen-v1.6.7.1-DEV.zip)

It works! Thx
