### ISSUE TITLE
VPN Code account error

### ISSUE THREAD

**Issue by krnchawla001** [rzc0d3r/ESET-KeyGen#233]
![image](https://github.com/user-attachments/assets/08ca2e97-8dda-448b-9dd4-fe5b93922390)

[   OK   ] Account successfully confirmed!

[  INFO  ] [SMALL BUSINESS] Request sending...
[ FAILED ] Traceback (most recent call last):
  File "C:\Program Files\Google\Chrome Beta\Application\modules\EsetTools.py", line 103, in sendRequestForKey
    if button.get_attribute('innerText').strip().lower() == 'continue':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 177, in get_attribute
    _load_js()
  File "C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 48, in _load_js
    getAttribute_js = pkgutil.get_data(_pkg, "getAttribute.js").decode("utf8")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\pkgutil.py", line 453, in get_data
    return loader.get_data(resource_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\getAttribute.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Google\Chrome Beta\Application\main.py", line 342, in main
    EK_obj.sendRequestForKey()
  File "C:\Program Files\Google\Chrome Beta\Application\modules\EsetTools.py", line 118, in sendRequestForKey
    raise RuntimeError('Request sending error!!!')
RuntimeError: Request sending error!!!

**Comment by rzc0d3r** [comment]
I see you are using the source code, the reason is the lack of some getAttribute.js, most likely you have an old version of selenium. Update it via pip

**Comment by rzc0d3r** [comment]
pip uninstall selenium
pip install selenium
