### ISSUE TITLE
FAILED  Traceback (most recent call last)

### ISSUE THREAD

**Issue by syarz** [rzc0d3r/ESET-KeyGen#234]
This is the issu, somebody help !!

---- Main Menu ----

1 - Settings
2 - Start
3 - Exit

>>> 2

-- Updater --

[  WARN  ] Project update is available up to version: v1.5.2.3
[  WARN  ] If you want to download the update run this file with --update argument

-- Browsers Initializer --

[  INFO  ] Initializing Google Chrome for Windows

DevTools listening on ws://127.0.0.1:56903/devtools/browser/a698d17f-d53d-42aa-925b-5d263c6d84da

-- KeyGen --

[  INPT  ] Enter the email address you have access to: dipar19365@ruhtan.com
[   OK   ] Mail has the correct syntax!

[  INFO  ] [EMAIL] Register page loading...
[   OK   ] [EMAIL] Register page is loaded!

[  INFO  ] Bypassing cookies...
[   OK   ] Cookies successfully bypassed!

[  INFO  ] [PASSWD] Register page loading...
[   OK   ] [PASSWD] Register page is loaded!

[  INPT  ] Enter the link to activate your account, it will come to the email address you provide: https://login.eset.com/link/confirmregistration?token=b0531b2b-b1fe-487f-918a-e8c513071085
[   OK   ] ESET-HOME-Token: b0531b2b-b1fe-487f-918a-e8c513071085

[  INFO  ] Account confirmation is in progress...
[   OK   ] Account successfully confirmed!

[  INFO  ] [ESET HOME] Request sending...
[ FAILED ] Traceback (most recent call last):
  File "modules\EsetTools.py", line 102, in sendRequestForKey
  File "selenium\webdriver\remote\webdriver.py", line 414, in execute_script
  File "selenium\webdriver\remote\webdriver.py", line 354, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 229, in check_response
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of undefined (reading 'click')
  (Session info: chrome=130.0.6723.91)

**Comment by syarz** [comment]
Fixed it. It says
[ INFO ] Account confirmation is in progress...
[ OK ] Account successfully confirmed!
You have to open eset login page manually and reset the password with the same temp email. Just keep tempmail open so that you can receive the reset link,
