### ISSUE TITLE
[ FAILED ] on v1.0.8.3 (181023-0013)

### ISSUE THREAD

**Issue by guiteubeuh** [rzc0d3r/ESET-KeyGen#25]
_Hello there,

On Win11 Pro up to date druiver installation Ok but then just FAILED:_

-- Chrome Driver Auto-Installer v1.1.3 (151023-2234) by rzc0d3r --

[  INFO  ] Chrome version: 118.0.5993.72
[  INFO  ] Chrome driver version: None

[ FAILED ] Chrome driver not detected, download attempt...

[   OK   ] Found a suitable version for your system!

[  INFO  ] Download attempt...
[   OK   ] The Сhrome driver was successfully downloaded and unzipped!

Press Enter to continue...

-- ESET KeyGen pre-release v1.0.8.3 (181023-0013) by rzc0d3r --

[ FAILED ]
Press Enter...

**Comment by rzc0d3r** [comment]
Try it [debug.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/13033422/debug.zip)
**Run with cmd!!!**

**Comment by guiteubeuh** [comment]
thank you for your reply,here's the cmd debug (I also disabled my firewall just in case):

[ FAILED ]
Traceback (most recent call last):
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000280B627D610>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.1secmail.com <http://www.1secmail.com>', port=443): Max retries exceeded with url: /api/v1/?action=genRandomMailbox&count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000280B627D610>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Thin\Downloads\Compressed\debug\ESET KeyGen.py", line 35, in register
    r = requests.get(url)
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thin\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.1secmail.com <http://www.1secmail.com>', port=443): Max retries exceeded with url: /api/v1/?action=genRandomMailbox&count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000280B627D610>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Thin\Downloads\Compressed\debug\ESET KeyGen.py", line 308, in <module>
    raise E
  File "C:\Users\Thin\Downloads\Compressed\debug\ESET KeyGen.py", line 285, in <module>
    email_obj.register()
  File "C:\Users\Thin\Downloads\Compressed\debug\ESET KeyGen.py", line 37, in register
    raise EmailConnectError
EmailConnectError


18 oct. 2023, 21:57 de ***@***.***:

**Comment by rzc0d3r** [comment]
It depends on the state of the mail server. Sometimes it is disabled, just try doing it later. Also, put python into firewall exceptions.
