### ISSUE TITLE
Firefox driver doesn't work on Linux

### ISSUE THREAD

**Issue by AdityaGarg8** [rzc0d3r/ESET-KeyGen#48]
```
[  INFO  ] Initializing firefox-driver for Linux
[ FAILED ] Traceback (most recent call last):
  File "/home/runner/work/ESET-KeyGen/ESET-KeyGen/ESET-KeyGen/main.py", line 71, in <module>
    driver = shared_tools.initSeleniumWebDriver('firefox')
  File "/home/runner/work/ESET-KeyGen/ESET-KeyGen/ESET-KeyGen/modules/shared_tools.py", line 93, in initSeleniumWebDriver
    driver = Firefox(options=driver_options, service=driver_service)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
```

This is the error

**Comment by AdityaGarg8** [comment]
Fixed by running as non root user

**Comment by rzc0d3r** [comment]
I added this to README.md

**Comment by rzc0d3r** [comment]
> I'm not aware whether it works as a non root user in Windows. Can you tell me whether your scripts works on Powershell admin and without admin.

one second

**Comment by rzc0d3r** [comment]
works.

**Comment by AdityaGarg8** [comment]
I guess they don't work with admin
