### ISSUE TITLE
решил я сгенерить себе номерок

### ISSUE THREAD

**Issue by borisorlov21** [rzc0d3r/ESET-KeyGen#51]
решил я сгенерить себе номерок и на мак и вин такая хрень
Last login: Sun Dec 10 23:50:42 on console
imacpro@iMac-Pro ~ % python3 /Users/imacpro/Desktop/ESET-KeyGen-main/main.py
-- Chrome Driver Auto-Installer v1.1.4 (171123-1640) by rzc0d3r --

[  INFO  ] Chrome version: 119.0.6045.199
[  INFO  ] Chrome driver version: 119.0.6045.105
[  INFO  ] Initializing chrome-driver for Linux

-- ESET KeyGen v1.0.9.2 (211123-1059) by rzc0d3r --

[  INFO  ] Mail registration...
[ FAILED ] Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x108ca0260>: Failed to establish a new connection: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.1secmail.com', port=443): Max retries exceeded with url: /api/v1/?action=genRandomMailbox&count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x108ca0260>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/imacpro/Desktop/ESET-KeyGen-main/modules/sec_email_api.py", line 16, in register
    r = requests.get(url)
        ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.1secmail.com', port=443): Max retries exceeded with url: /api/v1/?action=genRandomMailbox&count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x108ca0260>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/imacpro/Desktop/ESET-KeyGen-main/main.py", line 86, in <module>
    email_obj.register()
  File "/Users/imacpro/Desktop/ESET-KeyGen-main/modules/sec_email_api.py", line 18, in register
    raise SecEmailConnectError
modules.sec_email_api.SecEmailConnectError

Press Enter...

**Comment by rzc0d3r** [comment]
Нет связи с сервисом 1secmail. Он может уйди в обслуживание и не отвечать. Такое бывает. Попробуйте через пару часов.

**Comment by rzc0d3r** [comment]
Я проверил проект и он работает. Я в следующем обновлении добавлю вывод сообщения что сайт 1secmail не доступен.

**Comment by rzc0d3r** [comment]
> вы какой используете линукс

Незнаю. Я генерирую ключи через сервера github или же на Windows.

**Comment by borisorlov21** [comment]
вчера вечером и сейчас работает на мак каталина монтерей и вентура с впн  без вмп нет связи с сервером красные буквы наверно заблогировали мой айпи  и еще могут ли они както препятствовать зтой программе  в антивирусе виндоус уже заблокировали вас на гитхаб красной полосой вот

**Comment by rzc0d3r** [comment]
Советую вам не переживать. И использовать github actions. Как ими пользоваться описано в README.md. Очень удобно и быстро, а главное что все в облаке вам не нужно ничего устанавливать все сделает за вас!

**Comment by borisorlov21** [comment]
посмотрел несколько видео по github actions ничего непонял да уж

**Comment by rzc0d3r** [comment]
> посмотрел несколько видео по github actions ничего непонял да уж может нето смотрел

Просто сделайте форк моего проекта, открой его потом у себя на страничке гитхаба. Нажмите на кнопку Actions. Выберайте дальше workspace с именем ESET & Account generator (MAIN) нажимаете Run Workspace. И ждёте, после около 50-60с в вас в списках запусков будет этот запуск с галочкой нажимаете на него и там будут логи в них и будет ключ.

**Comment by borisorlov21** [comment]
благодарю за инструкцию попробовал получилось
👍🏻
я новичёк в гитхабе слышал что немцы сделали такой проект круто надо изучать
