### ISSUE TITLE
Process completed with exit code 1.

### ISSUE THREAD

**Issue by TrasserZero** [rzc0d3r/ESET-KeyGen#57]
[  INFO  ] Bypassing cookies...
[   OK   ] Cookies successfully bypassed!
[ FAILED ] Traceback (most recent call last):
  File "/home/runner/work/ESET-KeyGen/ESET-KeyGen/ESET-KeyGen/main.py", line 90, in <module>
    EsetReg.createAccount()
  File "/home/runner/work/ESET-KeyGen/ESET-KeyGen/ESET-KeyGen/modules/eset_register.py", line 49, in createAccount
    exec_js(f"{GET_EBID}('Email').value='{self.email_obj.get_full_login()}'")
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 408, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot set properties of null (setting 'value')
  (Session info: chrome-headless-shell=120.0.6099.109)

cat: './*ACCOUNTS.txt': No such file or directory
Error: Process completed with exit code 1.

**Comment by rzc0d3r** [comment]
**Try the new version [v1.1.0.0 (211223-1312)](https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.1.0.0-211223-1312) !!!**
