### ISSUE TITLE
handshake errors

### ISSUE THREAD

**Issue by MrMarvel** [rzc0d3r/ESET-KeyGen#81]
Windows 11
Python 3.12.1
Causes handshake errors: handshake failed; returned -1, SSL error code 1, net_error -101
```
PS C:\Users\Sergey\Downloads\ESET-KeyGen> py .\main.py

███████╗███████╗███████╗████████╗   ██╗  ██╗███████╗██╗   ██╗ ██████╗ ███████╗███╗   ██╗
██╔════╝██╔════╝██╔════╝╚══██╔══╝   ██║ ██╔╝██╔════╝╚██╗ ██╔╝██╔════╝ ██╔════╝████╗  ██║
█████╗  ███████╗█████╗     ██║      █████╔╝ █████╗   ╚████╔╝ ██║  ███╗█████╗  ██╔██╗ ██║
██╔══╝  ╚════██║██╔══╝     ██║      ██╔═██╗ ██╔══╝    ╚██╔╝  ██║   ██║██╔══╝  ██║╚██╗██║
███████╗███████║███████╗   ██║      ██║  ██╗███████╗   ██║   ╚██████╔╝███████╗██║ ╚████║
╚══════╝╚══════╝╚══════╝   ╚═╝      ╚═╝  ╚═╝╚══════╝   ╚═╝    ╚═════╝ ╚══════╝╚═╝  ╚═══╝

                                                Project Version: v1.3.0.1
                                                Project Devs: rzc0d3r, AdityaGarg8, k0re,
                                                              Fasjeit, alejanpa17, Ischunddu,
                                                              soladify

-- WebDriver Auto-Installer --

[  INFO  ] Google Chrome version: 121.0.6167.140
[  INFO  ] Google Chrome webdriver version: None

[ FAILED ] Google Chrome webdriver not detected, download attempt...

[   OK   ] Found a suitable version for your system!

[  INFO  ] Downloading...
[   OK   ] Google Chrome webdriver was successfully downloaded and unzipped!

Press Enter to continue...
[  INFO  ] Initializing chrome-webdriver for Windows

DevTools listening on ws://127.0.0.1:50712/devtools/browser/da2cfee6-9318-4550-b1c6-a941faf4e42c

-- KeyGen --

[  INFO  ] Mail registration...
[   OK   ] Mail registration completed successfully!

[  INFO  ] [EMAIL] Register page loading...
[   OK   ] [EMAIL] Register page is loaded!

[  INFO  ] Bypassing cookies...
[   OK   ] Cookies successfully bypassed!

[  INFO  ] [PASSWD] Register page loading...
[   OK   ] [PASSWD] Register page is loaded!

[  INFO  ] ESET-Token interception...
[   OK   ] ESET-Token: 647a848c-ee2b-47f4-936d-2afd2b764209

[  INFO  ] Account confirmation is in progress...
[0131/091938.231:ERROR:ssl_client_socket_impl.cc(974)] handshake failed; returned -1, SSL error code 1, net_error -101
[0131/091957.418:ERROR:ssl_client_socket_impl.cc(974)] handshake failed; returned -1, SSL error code 1, net_error -101
[ FAILED ] Traceback (most recent call last):
  File "C:\Users\Sergey\Downloads\ESET-KeyGen\main.py", line 125, in <module>
    EsetReg.confirmAccount()
  File "C:\Users\Sergey\Downloads\ESET-KeyGen\modules\eset_register.py", line 82, in confirmAccount
    uCE(self.driver, f"return typeof {GET_EBAV}('ion-button', 'robot', 'home-overview-empty-add-license-btn') === 'object'")
  File "C:\Users\Sergey\Downloads\ESET-KeyGen\modules\shared_tools.py", line 61, in untilConditionExecute
    raise RuntimeError('untilConditionExecute: the code did not return the desired value!')
RuntimeError: untilConditionExecute: the code did not return the desired value!
```

**Comment by Denis73d** [comment]
windows11 ?

**Comment by MrMarvel** [comment]
Yes, Windows 11

**Comment by Denis73d** [comment]
exactly the same error

**Comment by Denis73d** [comment]
works fine on windows 10

**Comment by Denis73d** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/discussions/80#discussion-6157646

**Comment by MrMarvel** [comment]
Yep, on Windows 10, Python 3.12.0 works fine
