### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Denis73d** [rzc0d3r/ESET-KeyGen#83]
FAILED ] Traceback (most recent call last):
  File "C:\ESET-KeyGen-main\main.py", line 125, in <module>
    EsetReg.confirmAccount()
  File "C:\ESET-KeyGen-main\modules\eset_register.py", line 82, in confirmAccount
    uCE(self.driver, f"return typeof {GET_EBAV}('ion-button', 'robot', 'home-overview-empty-add-license-btn') === 'object'")
  File "C:\ESET-KeyGen-main\modules\shared_tools.py", line 61, in untilConditionExecute
    raise RuntimeError('untilConditionExecute: the code did not return the desired value!')
RuntimeError: untilConditionExecute: the code did not return the desired value!

**Comment by rzc0d3r** [comment]
Try a VPN
