### ISSUE TITLE
Connection error on mail registration

### ISSUE THREAD

**Issue by lapaten** [rzc0d3r/ESET-KeyGen#84]
[  INFO  ] Mail registration...
[ FAILED ] Traceback (most recent call last):
  File "urllib3\connection.py", line 203, in _new_conn
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
TimeoutError: [WinError 10060] Próba połączenia nie powiodła się, ponieważ połączona strona nie odpowiedziała poprawnie po ustalonym okresie czasu lub utworzone połączenie nie powiodło się, ponieważ połączony host nie odpowiedział

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1096, in _validate_conn
  File "urllib3\connection.py", line 611, in connect
  File "urllib3\connection.py", line 218, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002D6791AE160>: Failed to establish a new connection: [WinError 10060] Próba połączenia nie powiodła się, ponieważ połączona strona nie odpowiedziała poprawnie po ustalonym okresie czasu lub utworzone połączenie nie powiodło się, ponieważ połączony host nie odpowiedział

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.1secmail.com', port=443): Max retries exceeded with url: /api/v1/?action=genRandomMailbox&count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002D6791AE160>: Failed to establish a new connection: [WinError 10060] Próba połączenia nie powiodła się, ponieważ połączona strona nie odpowiedziała poprawnie po ustalonym okresie czasu lub utworzone połączenie nie powiodło się, ponieważ połączony host nie odpowiedział'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "modules\sec_email_api.py", line 15, in register
    r = requests.get(url)
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.1secmail.com', port=443): Max retries exceeded with url: /api/v1/?action=genRandomMailbox&count=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002D6791AE160>: Failed to establish a new connection: [WinError 10060] Próba połączenia nie powiodła się, ponieważ połączona strona nie odpowiedziała poprawnie po ustalonym okresie czasu lub utworzone połączenie nie powiodło się, ponieważ połączony host nie odpowiedział'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 120, in <module>
    email_obj.register()
  File "modules\sec_email_api.py", line 17, in register
    raise SecEmailConnectError
modules.sec_email_api.SecEmailConnectError

Press Enter...

**Comment by AlienFreek** [comment]
same issue, seems like 1secmail isnt available right now

**Comment by Denis73d** [comment]
Yes, it stopped working

**Comment by rzc0d3r** [comment]
1secmail can sometimes be under maintenance. No need to worry. It lasts about 6-12 hours
